services:
  - type: web
    name: lonaloto
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /healthz
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: lonaloto-db
          property: connectionString

databases:
  - name: lonaloto-db
    plan: free
